-- MySQL Script generated by MySQL Workbench
-- Mon Aug  3 10:34:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `restaurante_db` ;

-- -----------------------------------------------------
-- Table `restaurante_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `restaurante_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `direccion` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`status_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`status_mesa` (
  `id_status_mesa` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `capacidad` TINYINT(2) NOT NULL,
  `id_status_mesa` INT NOT NULL,
  PRIMARY KEY (`id_mesa`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_mesa_status_mesa1_idx` (`id_status_mesa` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_status_mesa1`
    FOREIGN KEY (`id_status_mesa`)
    REFERENCES `restaurante_db`.`status_mesa` (`id_status_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `puesto` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `fecha_contratacion` DATE NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`status_pedido` (
  `id_status_pedido` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_status_pedido`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`metodo_pago` (
  `id_metodo_pago` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_metodo_pago`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_mesa` INT NOT NULL,
  `total` DECIMAL(10,2) NULL,
  `id_empleado` INT NULL,
  `id_metodo_pago` INT NULL,
  `id_status_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_pedido_empleado1_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_pedido_mesa1_idx` (`id_mesa` ASC) VISIBLE,
  INDEX `fk_pedido_status_pedido1_idx` (`id_status_pedido` ASC) VISIBLE,
  INDEX `fk_pedido_metodo_pago1_idx` (`id_metodo_pago` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `restaurante_db`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `restaurante_db`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_mesa1`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `restaurante_db`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_status_pedido1`
    FOREIGN KEY (`id_status_pedido`)
    REFERENCES `restaurante_db`.`status_pedido` (`id_status_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_metodo_pago1`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `restaurante_db`.`metodo_pago` (`id_metodo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`ingrediente` (
  `id_ingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `existencia` DECIMAL(10,2) NOT NULL,
  `unidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_ingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`producto_ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`producto_ingrediente` (
  `id_producto` INT NOT NULL,
  `id_ingrediente` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_ingrediente`),
  INDEX `fk_producto_ingrediente_ingrediente1_idx` (`id_ingrediente` ASC) VISIBLE,
  CONSTRAINT `fk_producto_ingrediente_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `restaurante_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_ingrediente_ingrediente1`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `restaurante_db`.`ingrediente` (`id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante_db`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_db`.`detalle_pedido` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NULL,
  `id_producto` INT NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_detalle_pedido_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_detalle_pedido_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `restaurante_db`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `restaurante_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
